# Generated by Django 4.2.3 on 2023-08-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogProfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
