# Generated by Django 4.2.3 on 2023-08-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogProfiles', '0004_alter_avatar_imagen_alter_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='No Avatar', upload_to='avatars/'),
        ),
    ]
