# Generated by Django 4.2.3 on 2023-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogProfiles', '0005_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
