# Generated by Django 4.2.3 on 2023-08-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogProfiles', '0006_alter_userprofile_avatar_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(default='https://'),
        ),
    ]
