# Generated by Django 4.2.3 on 2023-08-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogProfiles', '0007_remove_userprofile_email_userprofile_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
