# Generated by Django 4.2.3 on 2023-08-19 21:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='#Título', max_length=100)),
                ('header', models.CharField(default='#subtítulo', max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 8, 19, 21, 37, 14, 534552, tzinfo=datetime.timezone.utc))),
                ('content', models.TextField(blank=True, default='#Contenido', max_length=10000)),
                ('image', models.ImageField(default='#IMAGE', upload_to='posts/')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(default='#USER', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
