# Generated by Django 4.2.3 on 2023-08-16 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 18, 34, 54, 312243, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 18, 34, 54, 311242, tzinfo=datetime.timezone.utc)),
        ),
    ]
