# Generated by Django 4.2.3 on 2023-08-15 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 22, 8, 19, 389659, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 22, 8, 19, 388659, tzinfo=datetime.timezone.utc)),
        ),
    ]
