# Generated by Django 4.2.3 on 2023-08-19 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0002_alter_post_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 19, 23, 42, 37, 595074, tzinfo=datetime.timezone.utc)),
        ),
    ]
