# Generated by Django 4.2.3 on 2023-08-16 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0003_alter_post_options_alter_comentario_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 19, 52, 48, 327980, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 19, 52, 48, 326980, tzinfo=datetime.timezone.utc)),
        ),
    ]
