# Generated by Django 4.2.3 on 2023-08-16 23:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogPosts', '0005_alter_comentario_timestamp_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 23, 50, 17, 202447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='#Contenido', max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(default='#subtítulo', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='#IMAGE', upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 23, 50, 17, 201447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='#Título', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='#USER', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
