# Generated by Django 4.2.3 on 2023-08-16 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0009_alter_comentario_timestamp_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 13, 17, 7, 228828, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 13, 17, 7, 228828, tzinfo=datetime.timezone.utc)),
        ),
    ]
