# Generated by Django 4.2.3 on 2023-08-17 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0012_alter_comentario_timestamp_alter_post_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 23, 54, 18, 675216, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
