# Generated by Django 4.2.3 on 2023-08-16 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0013_post_header_alter_comentario_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 16, 20, 40, 877055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 16, 20, 40, 876055, tzinfo=datetime.timezone.utc)),
        ),
    ]
